### PR TITLE
If the target version of the Android app is smaller than Android M th…

### PR DESCRIPTION
**Pull request by GamesAgeddon**
…e ContextCompat.CheckSelfPermission returns always Permission.Granted.

Added the PermissionChecker for permission self checks in apps targeting Android under M.

Please take a moment to fill out the following:

Changes Proposed in this pull request:
- Check first which target version an Android app has before checking if permission is granted.
- PermissionChecker for target version under Android M

### CODE REVIEW

**Comment by jamesmontemagno** [comment]
Please re-target and build against 7.1 and remove all of your nuget updates.

**Comment by GamesAgeddon** [comment]
Thanks for your feedback :)

**Comment by jamesmontemagno** [comment]
There are still tons of changes as you added a bunch of NuGets that you don't need at all I think... can they be removed?

**Comment by jamesmontemagno** [comment]
The ideal way is just 1 file change

**Comment by GamesAgeddon** [comment]
The problem is the PermissionChecker utility class which is contained within the Xamarin.Android.Support.v4 NuGet package
(See the original documentation https://developer.android.com/reference/android/support/v4/content/PermissionChecker.html). 
And this nuget package has a lot of dependencies, namely: Xamarin.Android.Support.Media.Compat, Xamarin.Android.Support.Core.Utils, Xamarin.Android.Support.Core.UI, Xamarin.Android.Support.Fragment 
and Xamarin.Android.Support.Compat.

Unfortunately, I don't know a way to extract the PermissionChecker class from the support library package without introducing new dependencies. :-/
But if you know one, I would be very thankful to hear about it.

**Comment by jamesmontemagno** [comment]
Ah! I see, I will look into it then :)

**Comment by jamesmontemagno** [comment]
Cleaned it up and added it into master :) take a look

**Comment by GamesAgeddon** [comment]
Thanks. Looks good ;)

**Pull request closed without merging**
