### PR TITLE
Added Permissionhandling for iOS MPMediaLibrary

### PR DESCRIPTION
**Pull request by escamoteur**
Please take a moment to fill out the following:

Changes Proposed in this pull request:
Add Handling to check and request Permissions to MediaLibrary on IOS

### CODE REVIEW

**Comment by soroshsabz** [comment]
ITNOA

Hi,

@escamoteur Did you check all project that compile correctly? CI failed your PR!

**Comment by escamoteur** [comment]
will have to recheck

**Comment by soroshsabz** [comment]
@escamoteur you correct, I'm sorry.

**Comment by jamesmontemagno** [comment]
Fixing up build issues and such.

**Comment by escamoteur** [comment]
Hi, 
why is this PR not merged?

Cheers
Thomas

**Comment by jamesmontemagno** [comment]
It needs to be merged and I still need to assess it. I don't accept every PR that comes in right away. I have a large backlog.

**Comment by escamoteur** [comment]
Sorry, I did not want to be pushy James

**Pull request closed without merging**
