### PR TITLE
Refactor entire library to make linker safe on iOS/Android :)

### LINKED ISSUE #136: Apple rejects our binaries because of references to Location
When i submit my app to Apple to validate, i received App Store connect warning about that my app is missing NSLocationAlwaysUsageDescription.

The problem is doesn't use any of these permissions, but because the my app is references to Plugin.Permission and Plugin.Permission is referenced to some of LocationManager of iOS SDK, so they're forcing us to have a string in Info.plist file.

But if we put the string into Info.plist file, our App in AppStore will always show something like : "This app may use your location even when it isn't open, which can decrease device battery life". And this will definitely not making the client happy.

More worse, some of other libraries is referenced to this package unfortunately, so i have to copy and paste these libraries in our app and clone this package.

So my suggestion is we should split the permissions in this package into smaller package for avoiding unnecessary permission references. Something like Plugin.Permission.Core and Plugin.Permission.Camera - Plugin.Permissions.Location for example

### PR DESCRIPTION
**Pull request by jamesmontemagno**
Please take a moment to fill out the following:

Fixes #136  .

Changes Proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by ngalicoco** [comment]
@jamesmontemagno Is there nuget package for this release.. The last package I see is 3.0.0.12 released on May 23 2018

**Comment by ngalicoco** [comment]
@jamesmontemagno I will take this back.. so I am seeing lot of beta releases on nuget. Should we wait till the 6.0.0-beta is stable

**Comment by jamesmontemagno** [comment]
You can use 5.0 or 6.0 or just use Xamarin.Essentials 1.5.1 :)

**Comment by ngalicoco** [comment]
@jamesmontemagno Thanks.. so currently we are using Plugin.Permissions for checking and requesting permissions for geoloadtion and storage. So if we consume Xamarin.Essentials 1.5.1 we can totally remove references for Xam.Plugin , right ?

**Comment by jamesmontemagno** [comment]
yup :) https://docs.microsoft.com/en-us/xamarin/essentials/permissions

**Comment by ngalicoco** [comment]
@jamesmontemagno Thanks

**Comment by ngalicoco** [comment]
@jamesmontemagno After I removed nuget references for Xam.Plugin.Permissions and using X.Essentials permissions , our location implementation is working. But We also use Xam.Plugin.Media, which in turn references to Permissions plugin. Not sure if apple will warn us about missing purpose string for location in info.plist. Is there a X.Essentials alternative for Media plugin too

**Comment by jamesmontemagno** [comment]
the latest beta of the media plugin https://www.nuget.org/packages/Xam.Plugin.Media/5.0.0-beta uses  Xamarin.Essentials :)

**Comment by ngalicoco** [comment]
@jamesmontemagno Even after getting rid of Xam.Permission Plugin and update the Media plugin to 5.0.0-beta(which references to Essentials), we still got the same warning as before doing all this, from apple

_Dear Developer,

We identified one or more issues with a recent delivery for your app, "CoConstruct" 3.8.2 (2006). Your delivery was successful, but you may wish to correct the following issues in your next delivery:

ITMS-90683: Missing Purpose String in Info.plist - Your app's code references one or more APIs that access sensitive user data. The app's Info.plist file should contain a NSLocationAlwaysUsageDescription key with a user-facing purpose string explaining clearly and completely why your app needs the data. Starting Spring 2019, all apps submitted to the App Store that access user data are required to include a purpose string. If you're using external libraries or SDKs, they may reference APIs that require a purpose string. While your app might not use these APIs, a purpose string is still required. You can contact the developer of the library or SDK and request they release a version of their code that doesn't contain the APIs. Learn more (https://developer.apple.com/documentation/uikit/core_app/protecting_the_user_s_privacy).

After you’ve corrected the issues, you can upload a new binary to App Store Connect.

Best regards,

The App Store Team_

We have both these in our application info.plist
- NSLocationWhenInUseUsageDescription
- NSLocationAlwaysAndWhenInUseUsageDescription

**Comment by MKGNZ** [comment]
You are missing: NSLocationAlwaysUsageDescription  It clearly says that you need this string. Also it has to be a better message. I had that issue because they didn't like the message. Don't just say "We need to access your location" but something like: "We need to access your location all the time because ............."

**Comment by ngalicoco** [comment]
@MKGNZ  Our application doesn't location always, just when we need it.
@jamesmontemagno  Sorry about my previous comment. We have accidently uploaded the old build to Test Flight via our devops pipelines which still has the Xam.Permissions plugin. After uploading the latest build the warning is gone. Thanks for your responses. Really appreciate it.

**Pull request merged**
