### PR TITLE
Initial support for tvOS

### PR DESCRIPTION
**Pull request by diegostamigni**
**Changes Proposed in this pull request:**
- Initial support for Apple tvOS platform

### CODE REVIEW

**Comment by diegostamigni** [comment]
@jamesmontemagno any update on this? any change you want me to make?

**Comment by jamesmontemagno** [comment]
Is there no way to combine the ios implementation with the tvOS ones? they are similar if not the same...

You can do something like: https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Xamarin.Essentials.csproj#L82-L95

**Comment by diegostamigni** [comment]
Leave it with me, I have an idea 👌

Regards,
Diego

**Comment by diegostamigni** [comment]
Right @jamesmontemagno I've unified iOS and tvOS under a .apple.cs shared file. You'll see in the code changes that I'm returning `Permissions.Unknown` when something isn't supported by tvOS but I wonder if we should rather throw. Up to you, if you like throwing let me know and I'll do that instead.

**Comment by jamesmontemagno** [comment]
If it is something not support it should return Granted I think. This is what I do on iOS/Android

**Comment by diegostamigni** [comment]
Fair enough, I’ll change to that then

Regards,
Diego

**Comment by diegostamigni** [comment]
Back to you @jamesmontemagno .. all changes applied 😄

**Comment by jamesmontemagno** [comment]
Made some small edits, mostly just trying to get CI to kick off :)

**Comment by diegostamigni** [comment]
Super cool 👍

**Comment by diegostamigni** [comment]
Anything I can do to help getting this merged in @jamesmontemagno ?

**Pull request merged**
